# Generated by Django 4.2.1 on 2023-05-30 14:11

from django.db import migrations, models
import tgBot.functions.data_base_functions


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senddata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tgBot.functions.data_base_functions.DbFunc.get_upload_path, verbose_name='Файл'),
        ),
    ]
